### ISSUE TITLE
Controller Not Responding in Linux

### ISSUE THREAD

**Issue by ahearnkyle** [ahearnkyle/GimbalProject#1]
we are attempting to connect the Xbox one controller to a Linux machine and we get zero responses. Using the USB adapter we get no response from and when we use the Bluetooth that the controller comes with it it will connect to the computer then immediately disconnect.

**Comment by ahearnkyle** [comment]
https://www.maketecheasier.com/set-up-xbox-one-controller-ubuntu/ This link says for ubuntu, but I have researched and it can be installed on to Raspbian. This drive software allow compatibility with Xbox 360 controller as well and it is really easy to install.

**Comment by kenton-dover** [comment]
I was able to get the xbox one controller to connect over bluetooth. It did take a little bit of work to get it configured. I used <code>bluetoothctl</code> to try to connect it and got the following.

[bluetooth]# scan on
Discovery started
[CHG] Controller A0:A8:CD:62:6B:E5 Discovering: yes
[NEW] Device 5C:BA:37:D5:2C:86 Xbox Wireless Controller
[CHG] Device 6C:35:74:9D:B9:30 RSSI: -82
[CHG] Device 6C:35:74:9D:B9:30 ManufacturerData Key: 0x004c
[CHG] Device 6C:35:74:9D:B9:30 ManufacturerData Value:
  0c 0e 00 e9 d2 99 c0 cb 2d 92 cf ea bb af 26 c5  ........-.....&.
  10 05 0b 10 46 12 ec                             ....F..         
[CHG] Device 5C:BA:37:D5:2C:86 RSSI: -55
[CHG] Device 5C:BA:37:D5:2C:86 RSSI: -45
[bluetooth]# pair 5C:BA:37:D5:2C:86
Attempting to pair with 5C:BA:37:D5:2C:86
[CHG] Device 5C:BA:37:D5:2C:86 Connected: yes
[CHG] Device 5C:BA:37:D5:2C:86 ServicesResolved: yes
[CHG] Device 5C:BA:37:D5:2C:86 Paired: yes
Pairing successful
[CHG] Device 5C:BA:37:D5:2C:86 ServicesResolved: no
[CHG] Device 5C:BA:37:D5:2C:86 Connected: no
[CHG] Device 5C:BA:37:D5:2C:86 RSSI: -53


The controller paired and then immediately disconnected. After doing some digging I updated the firmware for the controller using the xbox accessories app on windows 10. Then retried connecting to only get the same result. 

I found out that the kernel module for the xpad driver wasnt loaded correctly so I used <code>modprobe</code> to load it for the session (reboot removes it). I tried to connect again and still nothing. 

After searching around for a bit it was recommended to disable_ertm which you do by running <code>echo 1 > /sys/module/bluetooth/parameters/disable_ertm</code> while logged into root not with sudo(<code>sudo su</code>). After that I was able to get the controller to connect

Things that need done: The controller connects with an android interface over bluetooth meaning that at least the select button might not work if not more. 

> Yes, that's because the controller exposes an Android-friendly mapping over Bluetooth since the November firmware update.

> This is also the reason that some special buttons like back don't work correctly in some applications. They are now HID Consumer usages rather than HID Button usages. This is required to get the desired back and home behaviour on Android's default keymap.

> I believe an SDL2 patch has been checked in to fix the inability to use consumer buttons in controller configurations.

That was stated back in dec 2016 so who knows if its been fixed as of yet. There is this issue for the windows 10 connector https://github.com/paroj/xpad/issues/14#issuecomment-249609916 so it might be worth looking into. 

The only thing left to do is to get the button mapping/configuration sorted out.

When waking the controller from sleep it immediately pairs again so that's good.

**Comment by kenton-dover** [comment]
input_device = "Xbox Wireless Controller"
input_driver = "udev"

input_up_btn = "h0up"
input_right_btn = "h0right"
input_down_btn = "h0down"
input_left_btn = "h0left"

input_a_btn = "0"
input_b_btn = "1"
input_x_btn = "2"
input_y_btn = "3"

input_l_btn = "4"
input_l3_btn = "8"
input_l2_axis = "+2"

input_r_btn = "5"
input_r3_btn = "9"
input_r2_axis = "-3"

input_l_y_plus_axis = "+1"
input_l_x_plus_axis = "+0"
input_l_y_minus_axis = "-1"
input_l_x_minus_axis = "-0"

input_r_y_plus_axis = "+4"
input_r_x_plus_axis = "+3"
input_r_y_minus_axis = "-4"
input_r_x_minus_axis = "-3"

input_start_btn = "7"
input_select_btn = "6"

input_enable_hotkey_btn = "6"

input_reset_btn = "1"
input_exit_emulator_btn = "7"

input_save_state_btn = "4"
input_load_state_btn = "5"
input_state_slot_increase_btn = "h0right"
input_state_slot_decrease_btn = "h0left"

input_menu_toggle_btn = "2"

EDIT
These settings were for an RPi2 with a Bluetooth dongle attached. When swapping over to an RPi3, these button settings were no longer valid and the select button no longer throws response in EmulationStation or in JSTest.

**Comment by kenton-dover** [comment]
After further testing it seems that the windows 10 dongle for the controller will not work. While there is some development on the topic it stalled in 2016. The bluetooth however works flawlessly. once paired the device auto pairs after reboot and after sleep. it requires no user action other than turning on the controller. The buttons all seem to work they just need mapped to keyboard keys.
