### ISSUE TITLE
Investigate the JoystickSetupDialog.java

### ISSUE THREAD

**Issue by ahearnkyle** [ahearnkyle/GimbalProject#13]
Some of these classes in the old code we do not understand what they really are doing. The JoystickSetupDialog class should be investigate so that we know what the exact function of the class is. Post your findings this will be later used for redeveloping this code in python

**Comment by kenton-dover** [comment]
The file sets up a couple different buttons that for our application might not work since we don't have a screen to display it on. It has an option to load or save configuration for the joystick although I could not find an actual way to edit the config. The only thing that I think that it is doing is allowing you to edit the list of controllers that are setup with the system which is stored in a config file. The main thing that this file does is get a list of joysticks attached to the system and allow you to use the one specified. by putting it in the config file.

It does have a way to set what buttons do what on the joystick it looks like. I don't think we will need this functionality

**Comment by ahearnkyle** [comment]
would this be any help for developing the web page or no?

**Comment by kenton-dover** [comment]
I do not think it will be helpful
