### ISSUE TITLE
Web Socket testing

### ISSUE THREAD

**Issue by kenton-dover** [ahearnkyle/GimbalProject#8]
We need to determine what type of web socket the old code uses (tcp or udp) and then gather a list of the commands the the controller for the gimbal can take. We also need to determine what the controller sends back. 

The coding would be done with the standard python socket module.

**Comment by ahearnkyle** [comment]
The way so far that I see that the gimbals and "joysticks" are getting detected and connected are by configuration files. So every time the code run you need to have the config files set up to the amount of controllers or gimbals that you have. This is where we need to create our auto detect for the gimbals. (This was found in GimbalCotrollerGui.java) 

Once the controller config file is read a instance of the "Joystick" I am unable to to find documentation on the Joystick stuff because it is an external library that was added to the code. 

Then the gimbal config file will be read. In this file it will retrieve the ip addresses and the port numbers and adds them into an array.  After all the ip addresses and port numbers have been retrieved the code will iterate through the array and create a connection to each of the gimbals.

**Comment by ahearnkyle** [comment]
The code in the zip folder can not be run correctly due to the fact of the java version that is used. Because we are on Java 8 we can not read a 32-bit dll file that is required for the joystick lib. 

Once the gimbal is connected it just send packets to the gimbals that contains command (not sure what they are map to yet.) along with data(not sure what the data is used for yet.). The gimbal then just waits for a request. With this functionality it seems to be a TCP server. This can be observed in the GimbalConnection.java in the sendPacket method. (Line 697)

**Comment by kenton-dover** [comment]
After looking at it further it is defiantly tcp. I emailed moog to see if they would be willing to give us any documentation that they might have.
